apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik3
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v34.3.0
    helm:
      releaseName: traefik3
      valuesObject:    
        ingressClass:  # @schema additionalProperties: false
          enabled: true
          isDefaultClass: false
          name: "traefik3"
        experimental:
          abortOnPluginFailure: false
          fastProxy:
            enabled: false
            debug: false
          kubernetesGateway:
            enabled: false
          plugins: 
            traefik-oidc-auth:
              moduleName: "github.com/sevensolutions/traefik-oidc-auth"
              version: "v0.7.0"
            coraza-http-wasm-traefik:
              moduleName: "github.com/jcchavezs/coraza-http-wasm-traefik"
              version: "v0.3.0"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: false
