apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.*
    helm:
      releaseName: vault
      valuesObject:    
        ui:
          enabled: true
          publishNotReadyAddresses: true
          activeVaultPodOnly: false
          serviceType: "ClusterIP"
          serviceNodePort: null
          externalPort: 8200
          targetPort: 8200
        ingress:
          enabled: true
          activeService: true
          hosts:
            - host: vault.server
              paths: []
      

  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: false