apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coder
    # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true
  source:
    chart: coder
    repoURL: https://helm.coder.com/v2
    targetRevision: 2.18.4
    helm:
      releaseName: coder
      valuesObject:    
        coder:
          envUseClusterAccessURL: true
          replicaCount: 1
          workspaceProxy: false
          ingress:
            enable: true
            host: "coder.ffd.link"
            wildcardHost: "*.coder.ffd.link"
            tls:
              enable: true
              secretName: "ffd-link-tls"
              wildcardSecretName: "ffd-link-tls"
          env: 
          - name: CODER_PG_CONNECTION_URL
            valueFrom:
              secretKeyRef:
                # You'll need to create a secret called coder-db-url with your
                # Postgres connection URL like:
                # postgres://coder:password@postgres:5432/coder?sslmode=disable
                name: coder-db-url
                key: url
          - name: "CODER_ACCESS_URL"
            value: "https://coder.ffd.link"
          - name: "CODER_WILDCARD_ACCESS_URL"
            value: "*.coder.ffd.link"
         
