apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coder
    # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.*.*
    helm:
      releaseName: postgresql
      valuesObject:  
        volumePermissions:
          enabled: true
        tls:
          enabled: false
        global:
          postgresql:
            auth:
              existingSecret: "postgresql-auth"
