apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coder
    # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true
  source:
    chart: coder
    repoURL: https://helm.coder.com/v2
    targetRevision: 2.18.4
    helm:
      releaseName: coder
      valueFiles: 
        - coder-values.yaml
      ignoreMissingValueFiles: true
