---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix
  annotations:
    argocd.argoproj.io/sync-wave: "0"

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-mas-zitadel-config
  namespace: matrix
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: matrix-mas-zitadel-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        zitadel.yaml: |
          upstream_oauth2:
            providers:
              - id: 01ARZ3NDEKTSV4RRFFQ69G5FAV
                human_name: "FFD Link"
                issuer: "https://idp.ffd.link"
                client_id: "{{ .client_id }}"
                client_secret: "{{ .client_secret }}"
                token_endpoint_auth_method: client_secret_basic
                scope: "openid profile email"
                claims_imports:
                  subject:
                    template: "{{ `{{ user.sub }}` }}"
                  localpart:
                    action: require
                    template: "{{ `{{ user.preferred_username }}` }}"
                  displayname:
                    action: suggest
                    template: "{{ `{{ user.name }}` }}"
                  email:
                    action: suggest
                    template: "{{ `{{ user.email }}` }}"
                    set_email_verification: import

  data:
    - secretKey: client_secret
      remoteRef:
        key: kubernetes/matrix/zitadel
        property: client_secret
    - secretKey: client_id
      remoteRef:
        key: kubernetes/matrix/zitadel
        property: client_id
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: matrix

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  source:
    repoURL: ghcr.io/element-hq/ess-helm
    chart: matrix-stack
    targetRevision: 26.5.1

    helm:
      releaseName: matrix
      valuesObject:
        serverName: ffd.link

        ingress:
          className: traefik
          tlsEnabled: true
          tlsSecret: ffd-link-tls
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"

        storage:
          storageClassName: longhorn
          resourcePolicy: keep

        postgres:
          enabled: true
          storage:
            size: 10Gi
            storageClassName: longhorn

        matrixAuthenticationService:
          enabled: true

          ingress:
            host: matrix-auth.ffd.link
            className: traefik
            tlsSecret: ffd-link-tls
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"

          additional:
            zitadel.yaml:
              configSecret: matrix-mas-zitadel-config
              configSecretKey: zitadel.yaml

          syn2mas:
            enabled: false
            dryRun: false

        synapse:
          ingress:
            host: matrix.ffd.link
            className: traefik
            tlsSecret: ffd-link-tls
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"

          media:
            storage:
              size: 50Gi
              storageClassName: freenas-nfs-csi

          logging:
            rootLevel: WARNING

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 768Mi

        wellKnownDelegation:
          enabled: true

          ingress:
            className: traefik
            tlsSecret: ffd-link-tls
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"

        elementWeb:
          enabled: true

          ingress:
            host: chat.ffd.link
            className: traefik
            tlsSecret: ffd-link-tls
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"

    

          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

        matrixRTC:
          enabled: false

        hookshot:
          enabled: false

        elementAdmin:
          enabled: true
          ingress:
            host: admin-matrix.server
            className: traefik
            tlsSecret: ffd-link-tls
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
