apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: trust-manager
    repoURL: https://charts.jetstack.io
    targetRevision: "*"
    helm:
      releaseName: trust-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  
  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true