apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pre-zitadel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/ekozan/agrocd-home.git
    targetRevision: HEAD
    path: ./infra/pre-zitadel
   
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true