apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-truenas-smb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"    # ← 3 → 4
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: democratic-csi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: democratic-csi
    repoURL: https://democratic-csi.github.io/charts/
    targetRevision: 0.15.1
    helm:
      releaseName: democratic-csi
      valuesObject:
        driver:
          existingConfigSecret: democratic-csi-config
          config:
            driver: freenas-smb    # ← stub obligatoire
        csiDriver:
          name: "org.democratic-csi.smb"
          fsGroupPolicy: File
        node:
          driver:
            extraVolumeMounts:
              - name: mount-cifs
                mountPath: /usr/local/sbin/mount.cifs   
                readOnly: true
          extraVolumes:
            - name: mount-cifs
              hostPath:
                path: /usr/sbin/mount.cifs
                type: File
        storageClasses:
          - name: freenas-smb-csi
            defaultClass: false
            reclaimPolicy: Delete
            volumeBindingMode: Immediate
            allowVolumeExpansion: true
            parameters:
              fsType: cifs
              csi.storage.k8s.io/node-stage-secret-name: democratic-csi-smb-creds
              csi.storage.k8s.io/node-stage-secret-namespace: democratic-csi
            mountOptions:
              - noatime
              - nobrl
              - cache=none
              - vers=3.0
              - uid=0
              - gid=0
              - file_mode=0777
              - dir_mode=0777
            secrets:
              provisioner-secret:
              controller-publish-secret:
              node-stage-secret:
              node-publish-secret:
              controller-expand-secret:
