apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
    # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.*.*
    helm:
      releaseName: gitea
      valuesObject:  
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: true
          global:
            postgresql:
              service:
                ports:
                  postgresql: 5432
          primary:
            persistence:
              size: 10Gi
        redis:
          enabled: true
          architecture: standalone
          master:
            count: 1
        
        redis-cluster:
          enabled: false