apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
    # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.6.1
    helm:
      releaseName: gitea
      valuesObject: 
        image:
          tag: 1.23.0 
        ingress:
          enabled: true
          hosts:
            - host: git.ffd.link
              paths:
                - path: /
                  pathType: Prefix
        gitea:
          config:
            server: 
              ROOT_URL: https://git.ffd.link
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: true
          global:
            postgresql:
              service:
                ports:
                  postgresql: 5432
          primary:
            persistence:
              size: 10Gi
        redis:
          enabled: true
          architecture: standalone
          master:
            count: 1
        redis-cluster:
          enabled: false
        actions:
          enabled: true
          provisioning:
            enabled: true
