apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-smb-creds
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: democratic-csi-smb-creds
    creationPolicy: Owner
  data:
    - secretKey: mount_flags
      remoteRef:
        key: kubernetes/democratic-csi/smb-credentials
        property: mount_flags
