apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-config
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: democratic-csi-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: "{{ .config }}"
  data:
    - secretKey: config
      remoteRef:
        key: kv/kubernetes/democratic-csi/smb
        property: config
