apiVersion: external-secrets.io/v1
kind: ClusterSecretStores
metadata:
  name: openbao-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://openbao.ffd.link"
      path: "kv/kubernetes"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
